# Type stubs for easyocr
from typing import Any, List, Tuple, Union

import numpy as np
from PIL import Image

class Reader:
    def __init__(
        self,
        lang_list: List[str] = ['en', 'ch_sim'],
        gpu: bool = True,
        model_storage_directory: Union[str, None] = None,
        download_enabled: bool = True,
        recognizer: bool = True,
        detector: bool = True,
        verbose: bool = True,
        quantize: bool = True,
        cudnn_benchmark: bool = False,
    ) -> None: ...
    
    def readtext(
        self,
        image: Union[str, np.ndarray, Image.Image],
        decoder: str = 'greedy',
        beamWidth: int = 5,
        batch_size: int = 1,
        workers: int = 0,
        allowlist: Union[str, List[str], None] = None,
        blocklist: Union[str, List[str], None] = None,
        detail: int = 1,
        rotation_info: Union[List[float], None] = None,
        paragraph: bool = False,
        min_size: int = 10,
        contrast_ths: float = 0.1,
        adjust_contrast: float = 0.5,
        filter_ths: float = 0.003,
        text_threshold: float = 0.7,
        low_text: float = 0.4,
        link_threshold: float = 0.4,
        canvas_size: int = 2560,
        mag_ratio: float = 1.0,
        slope_ths: float = 0.1,
        ycenter_ths: float = 0.5,
        height_ths: float = 0.5,
        width_ths: float = 0.5,
        y_ths: float = 0.5,
        x_ths: float = 1.0,
        add_margin: float = 0.1,
        x_margins: int = 10,
        y_margins: int = 10,
        threshold: float = 0.2,
        box_threshold: float = 0.7,
        output_format: str = 'standard',
        **kwargs: Any,
    ) -> List[Tuple[List[List[int]], str, float]]: ...

def readtext(
    image: Union[str, np.ndarray, Image.Image],
    languages: List[str] = ['en', 'ch_sim'],
    decoder: str = 'greedy',
    beamWidth: int = 5,
    batch_size: int = 1,
    workers: int = 0,
    allowlist: Union[str, List[str], None] = None,
    blocklist: Union[str, List[str], None] = None,
    detail: int = 1,
    rotation_info: Union[List[float], None] = None,
    paragraph: bool = False,
    min_size: int = 10,
    contrast_ths: float = 0.1,
    adjust_contrast: float = 0.5,
    filter_ths: float = 0.003,
    text_threshold: float = 0.7,
    low_text: float = 0.4,
    link_threshold: float = 0.4,
    canvas_size: int = 2560,
    mag_ratio: float = 1.0,
    slope_ths: float = 0.1,
    ycenter_ths: float = 0.5,
    height_ths: float = 0.5,
    width_ths: float = 0.5,
    y_ths: float = 0.5,
    x_ths: float = 1.0,
    add_margin: float = 0.1,
    x_margins: int = 10,
    y_margins: int = 10,
    threshold: float = 0.2,
    box_threshold: float = 0.7,
    output_format: str = 'standard',
    **kwargs: Any,
) -> List[Tuple[List[List[int]], str, float]]: ...